apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ume0344/cd-containerized-microservices.git
    targetRevision: HEAD
    path: microservices
  destination: 
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
