apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app2
  name: microservice2-deployment
spec:
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: microservice2
          image: microservice2:10
          ports:
            - containerPort: 5002
