apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice1
  name: microservice1-deployment
spec:
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - name: microservice1
          image: umehabiba04/microservice1:10
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice1-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: microservice1
  type: ClusterIP
